apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce #ReadWriteMany #Read
  storageClassName: ebs-sc-gopal #this is the storage class name we got it from the storage class we created earlier
  resources:
    requests:
      storage: 4Gi #the max storage size will be 4Gi