apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: mysql
spec:
  replicas: 1 #it will deploy one single pod of mysql db
  selector:
    matchLabels:
      app: mysql 
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
        - name: mysql 
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password
          ports:
            - containerPort: 3306