#kubectl apply -f mysql.deployment 
apiVersion: apps/v1 #it will invoke this api
kind: Deployment #then it will use the Deployment Object
metadata:
  name: mysql #and create a deployment by the name as mysql
spec: #this is the specification about my deployment
  replicas: 1 #it will deploy one single pod of mysql db
  selector: 
    matchLabels: #all the 4 pod will have #this is like match expression
      app: mysql #this is the label in key value format
  template: #this template will be apply to all the 4 pod
    metadata:
      labels:
        app: mysql #same label i have put while creating this pod
    spec: #this tempalte contains specification
      containers:
        - name: mysql 
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d
      volumes: 
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: ebs-mysql-pv-claim
        - name: usermanagement-dbcreation-script
          configMap:
            name: usermanagement-dbcreation-script




















