#this is an yaml defination. run from top to bottom and left to right
apiVersion: v1 #all the communication to your k8s cluster happen through api. 
kind: Pod #which api i want to execute as of now we are deploying images so i want to create pod api Service Deployment Per cronj
metadata:
  name: nginx #when it is creating the pod object i need to define the name of the pod using meta data.
  labels:
    app: nginx 
spec: #inside the pod i want to deploy my image as container
  affinity:
    nodeAffinity:
    requiredDuringSchedulingIgnoreDuringExecution:
      nodeSelectorTerms
      - matchExpressings:
      - key: beta.kubernetes.io/arch
        operator: in 
        values:
         - amd64
  containers:
  - name: nginx 
    image: stacksimplify/kubenginx:1.0.0 #which image it should use to deploy the container
    ports:
    - containerPort: 80 #
  nodeSelector:
    kubernetes.io/os: windows